### ISSUE TITLE
MySSC: setup GitLab CI for Ansible project

### ISSUE THREAD

**Issue by patheard** [dto-btn/todo#40]
* Start docker-compose service.
* Start `play_all.yml` playbook run.
* Curl services to make sure they're responding.

**Stretch goal:**
* Run automated integration tests against the environment.

**Comment by patheard** [comment]
Setup gitlab-runner locally to build pipeline:
```bash
curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
sudo apt install gitlab-runner
gitlab-runner register
# provide details from GitLab repo

gitlab-runner exec docker job-stage-name
```

**Comment by patheard** [comment]
Various changes to get docker-in-docker (dind) to work for the gitlab-runner.

/etc/gitlab-runner/config.toml:
```toml
concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "dto-shared"
  url = "XXXXXXXXX"
  token = "XXXXXXXXX"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.docker]
    image = "docker:dind"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
```


Command to test locally:
```bash
gitlab-runner exec docker --docker-privileged --docker-volumes "/certs/client" play-all
```

Sample .gitlab-ci.yml:
```yaml
image: docker:19.03.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.5-dind

before_script:
  - apk add py-pip
  - apk add python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose

stages:
  - build

play-all:
  stage: build
  script:
    - cd test
    - docker-compose up -d
    - docker exec --user ansible test_control_1 /bin/bash -c 'ansible-playbook ~/ansible/play_all.yml -i ~/ansible/environments/docker --vault-id docker@~/ansible/test/vault-docker'
```
