### ISSUE TITLE
Investigate Honeycomb

### ISSUE THREAD

**Issue by patheard** [dto-btn/todo#86]
https://www.honeycomb.io/

**Comment by patheard** [comment]
Testing on nginx for MySSC 3.0 dev:

https://docs.honeycomb.io/getting-data-in/integrations/webservers/nginx/

```bash
# Install
wget -q -O honeytail https://honeycomb.io/download/honeytail/linux/1.622 && \
    echo '11b1f4ac722ea03f31608e40ff69b3fa6ee25182be3708d0db40fa5e70e70a65  honeytail' | sha256sum -c && \
    chmod 755 ./honeytail

# Start a tail process
honeytail --writekey=YOUR_API_KEY --dataset="MySSC 3.0" --parser=nginx \
  --file=/var/log/nginx/access.16.log \
  --nginx.conf=/etc/nginx/nginx.conf \
  --nginx.format=api_fmt \
  --backfill
```

**Comment by patheard** [comment]
Testing mysql integration, for MySSC 3.0 dev as well:

https://docs.honeycomb.io/getting-data-in/integrations/databases/mysql/logs/

**Comment by patheard** [comment]
Honeycomb is offering free support and accounts for services dealing with Covid:
https://twitter.com/lizthegrey/status/1242270948289626112

**Comment by patheard** [comment]
Look for docker image or create a custom image if one does not exist.
https://hub.docker.com/r/honeycombio/rdslogs/tags

**Comment by patheard** [comment]
Steps to confirm RDS Postgres logs could be consumed by Honeycomb from a pod:

**1 -** Followed this guide to create an [EKS with peered RDS (Postgres)](https://dev.to/bensooraj/accessing-amazon-rds-from-aws-eks-2pc3).

**2 -** Used [honeycombio/rdslogs k8s example](https://github.com/honeycombio/rdslogs/blob/master/kubernetes/rdslogs.yml) to create an rdslogs deployment.  Changes made were:

* create base64 encoded secrets (`echo -n SECRET_VALUE | base64`); and
* update command args:

```yaml
    spec:
      containers:
      - name: honeycomb-rdslogs
        image: honeycombio/rdslogs:latest
        command: ["/rdslogs"]
        args:
          - --region=<my-region>
          - --identifier=<my-db-identifier>
          - --writekey=$(WRITE_KEY)
          - --dataset=<honeycomb-dataset-name>
          - --output=honeycomb
          - --dbtype=postgresql
```

**3 -** Fed queries for logging with a postgres pod to confirm Honeycomb was receiving data:
```bash
kubectl run -i --tty --rm postgres --image=postgres --restart=Never -- /bin/bash
$ psql -h postgres-service -U USER -d DATABASE
```
